DATASET:
  TRAIN:
    TYPE: 'Mscoco'
    ROOT: './data/airiss/'
    IMG_PREFIX: 'train'
    ANN: 'train.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 45
      SCALE_FACTOR: 0.35
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: 0.3
  VAL:
    TYPE: 'Mscoco'
    ROOT: './data/airiss/'
    IMG_PREFIX: 'val'
    ANN: './val.json'
  TEST:
    TYPE: 'Mscoco_det'
    ROOT: './data/airiss'
    IMG_PREFIX: 'val'
    DET_FILE: './exp/json/test_det_yolo_airiss.json'
    ANN: './val.json'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: 'pretrained_models/fast_dcn_res50_256x192.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
  DCN:
    MODULATED: false
    DEFORM_GROUP: 1
    FALLBACK_ON_STRIDE: false
  STAGE_WITH_DCN:
  - false
  - true
  - true
  - true
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 270
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  DPG_MILESTONE: 210
  DPG_STEP:
  - 230
  - 250